kind: Deployment
apiVersion: apps/v1
metadata:
  name: signal-control-algorithm
  namespace: cx-test
  labels:
    app: signal-control-algorithm
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal-control-algorithm
  template:
    metadata:
      labels:
        app: signal-control-algorithm
    spec:
      containers:
        - name: signal-control-algorithm
          image: 'harbor.tianrang.com/city/cs-ai-light:feat-rt-0.1.0-build.1'
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
          env:
            - name: dev-mode
              value: 'false'
          resources:
            limits:
              memory: 512Mi
            requests:
              memory: 256Mi
      restartPolicy: Always